-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
hl.env("HYPRCURSOR_THEME", "AWESOMEWOBBMIKU2")
hl.env("XCURSOR_SIZE", "32")
hl.env("HYPRCURSOR_SIZE", "32")

hl.env("QT_QPA_PLATFORMTHEME", "kde")
hl.env("GTK_THEME", "Fluent-green-Dark-compact:dark")

local colorActive = "rgba(8de0b7ff)"
local colorInactive = "rgba(444444ff)"
local colorBackground = "rgba(dae6e0ff)"

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("sigma", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4,
    bezier = "sigma",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "sigma",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3,
    bezier = "sigma",
})

hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

hl.layer_rule({
    match = { namespace = "quickshell" },
    blur = true,
    ignore_alpha = 0,
})

hl.layer_rule({
    match = { namespace = "hyprpicker" },
    -- TODO: manual review — unmapped layer rule: "blur off"
})

hl.layer_rule({
    name = "vicinae-blur",
    match = {
        namespace = "vicinae",
    },
    blur = true,
    ignore_alpha = 0,
})

hl.layer_rule({
    name = "vicinae-no-animation",
    match = {
        namespace = "vicinae",
    },
    no_anim = true,
})

hl.layer_rule({
    name = "swaync-blur",
    match = {
        namespace = "swaync-control-center",
        namespace = "swaync-notification-window",
    },
    blur = true,
    ignore_alpha = 0,
})

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 0,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = colorActive,
            inactive_border = colorInactive,
        },
    },
    -- https://wiki.hypr.land/Configuring/Variables/#decoration
    decoration = {
        rounding = 4,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            vibrancy = 0.1696,
        },
    },
    group = {
        col = {
            border_active = colorActive,
            border_inactive = colorInactive,
            border_locked_active = colorActive,
            border_locked_inactive = colorInactive,
        },
        groupbar = {
            enabled = true,
            font_family = "JetBrainsMono Nerd Font",
            font_weight_active = "bold",
            font_size = 10,
            height = 12,
            indicator_height = 0,
            -- Background and Rounding
            col = {
                active = colorActive,
                inactive = colorBackground,
                locked_active = colorActive,
                locked_inactive = colorInactive,
            },
            gradients = true,
            gradient_rounding = 2,
            round_only_edges = false,
            gradient_round_only_edges = false,
            blur = true,
        },
    },
    animations = {
        enabled = true,
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
        -- #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
        -- animation = global,        1,     10,    quick
        -- animation = border,        1,     5.39,  easeOutQuint
        -- animation = windows,       1,     4.79,  easeOutQuint
        -- animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
        -- animation = windowsOut,    1,     1.49,  linear,       popin 87%
        -- animation = fadeIn,        1,     1.73,  almostLinear
        -- animation = fadeOut,       1,     1.46,  almostLinear
        -- animation = fade,          1,     3.03,  quick
        -- animation = layers,        1,     3.81,  easeOutQuint
        -- animation = layersIn,      1,     4,     easeOutQuint, fade
        -- animation = layersOut,     1,     1.5,   linear,       fade
        -- animation = fadeLayersIn,  1,     1.79,  almostLinear
        -- animation = fadeLayersOut, 1,     1.39,  almostLinear
        -- animation = workspaces,    1,     1.94,  almostLinear, fade
        -- animation = workspacesIn,  1,     1.21,  almostLinear, fade
        -- animation = workspacesOut, 1,     1.94,  almostLinear, fade
        -- animation = zoomFactor,    1,     7,     quick
    },
    -- Hyprland-run windowrule
    -- https://wiki.hypr.land/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})
