-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- polkit

-- fix kde apps on hyprland
-- https://www.lorenzobettini.it/2024/05/fixing-the-empty-open-with-in-dolphin-in-hyprland/
hl.env("XDG_MENU_PREFIX", "arch-")

-- wayland electron
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- yabridge
hl.env("WINELOADER", "/home/alvy/wine/wine-9.21-staging-tkg-amd64/bin/wine")

hl.on("hyprland.start", function()
    hl.exec_cmd("qs")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("swaync")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("halo")

    -- also for kde
    hl.exec_cmd("XDG_MENU_PREFIX=arch- kbuildsycoca6 --noincremental")
end)
