-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
-- Source: ~/.config/hypr/monitors-anticyclone.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors-anticyclone")

-- Source: ~/.config/hypr/style.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("style")
-- Source: ~/.config/hypr/behavior.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("behavior")
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
-- Source: ~/.config/hypr/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binds")
