-- 5070 ti setup
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
local hs = require("hyprsplit")
hs.monitor_priority( { "DP-6" , "DP-5" , "DP-3" } )

hl.monitor({
    output = "DP-6",
    mode = "3440x1440@144",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "DP-5",
    mode = "2560x1440",
    position = "-2560x0",
    scale = "1",
})

hl.monitor({
    output = "DP-3",
    mode = "1920x1080",
    position = "3440x540",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-5",
    mode = "1920x1080",
    position = "3440x-540",
    scale = "1",
})

-- igpu setup
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60",
    position = "760x-1080",
    scale = "2",
})

-- virtual
hl.monitor({
    output = "vir1080",
    mode = "1920x1080",
    position = "5360x360",
    scale = "1",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.device({
    name = "gaomon-gaomon-tablet-pen",
    output = "DP-3",
})

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprsplit { ... }
]]

hl.device({
    name = "weylus-stylus",
    output = "DP-3",
})

hl.device({
    name = "weylus-touch",
    output = "DP-3",
})

hl.config({
    cursor = {
        no_hardware_cursors = false,
    },
    -- hotplug
    -- drawing tablet
    -- weylus
})

